### ISSUE TITLE
Excessive Compartmentalization

### ISSUE THREAD

**Issue by Theocrat** [jorisschellekens/borb-examples#6] opened 2022-02-22 07:53 UTC
Hi, Joris

I am an Indian programmer working on some AI functionalities, such as OCR on scanned PDFs. I have just discovered borb, and I must say, I am deeply impressed by both the power and the level of detail in the documentation of this library. I would love to see this project grow and become a very well-integrated part of the Python family, recognized and respected by the developers who use Python. I think Borb holds the key to making PDF more easy to work with for all programmers around the world, and heaven knows there are a ton of scanned PDFs lying around which need work.

But there is something that I think is going to hold Borb back a lot. And that is the monstrous level of undue complexity in the package tree of the framework. I mean, just look at this:
```py
from borb.pdf.document.document import Document
```
Now you have to understand, for anyone who is familiar with the way the Python developers build their frameworks, this is about the ugliest single line of text in human history. And it will remain so embedded in their minds as the ugliest piece of writing they have seen until they import the PageLayout.

For instance, the `borb.pdf.document` package contains just two things - a name tree and the `borb.pdf.document.document` sub-package. This latter subpackage contains only one thing, and that is the `Document` class. So here is what I would like to know - _was there really a need for the subpackage to wrap the class?_

Instead of this thing - 
```mermaid
flowchart TD
    A[borb.pdf.document] --> B[borb.pdf.document.name_tree];
    A --> C[borb.pdf.document.document];
    C --> D[borb.pdf.document.document.Document];
    B --> E[borb.pdf.document.name_tree.NameTree];
    style D fill:#afe, stroke:#2b7;
    style E fill:#afe, stroke:#2b7;
```

Why can we not simply have:
```mermaid
flowchart TD
    A[borb.pdf.document] --> B[borb.pdf.document.NameTree];
    A --> C[borb.pdf.document.Document];
    style C fill:#afe, stroke:#2b7;
    style B fill:#afe, stroke:#2b7;
```

That would have made the importing of the modules so much simpler and easier, not to mention made so much more sense. The `borb.pdf.document.document` is a wrapper that only serves to wrap a single class. Can we not remove it altogether and replace it by the class it wraps? Does it hold the place for some other classes which will be entered in future? Was there a plan, since abandoned, to put more classes in there? 

### The Central Problem

As it stands, the `borb` package tree is immense, with most of the nodes having only one descendant. it is a cardinal rule in making a good tree that  all non-leaf nodes should have at least more than one descendant. The `borb` import statements are tiresome to remember, compared to other import statements.

Consider how the `skimage.io` and `skimage.draw` modules work. There is no further `io` subpackage inside the `skimage.io` - it directly yields us its classes and methods. We need something like that inside the `borb` module, a simple and easy-to-recall package tree which we can all love and use by instinct, like all the beloved packages in Python are used.

**Comment by jorisschellekens** [comment] 2022-02-22 09:55
Your issue is a duplicate of issue #34 on the main `borb` repository, with the following key differences:
- the original issue did not use the language you use ("ugliest line of code")
- the original issue made concrete suggestions in terms of how to change the existing code by means of changing the python module definition files. Whereas your issue makes no practical suggestions.

I certainly agree that the imports are unyielding. But I typically use an IDE (PyCharm) which does the heavy lifting for me in terms of imports. Even I haven't memorised the specific imports for my own library. 

You mentioned `skimage` as an example. Might I remind you that they have an entire team (slightly under 20 people) at their disposal. `borb` is built by a team of exactly 1 person. Me.

If more people would pay for my product, I could spend more time on it. And then I might get around to including features like this one.

For now, this is a low priority issue compared to including basic PDF functionality. 

I will close this issue as a duplicate.

Kind regards,
Joris Schellekens

**Closed as completed by jorisschellekens** 2022-02-22 09:55 UTC

**Comment by Theocrat** [comment] 2022-02-22 12:39
@jorisschellekens fair enough, I can understand your indignation at my choice of language. I do believe that removing the single-descendant non-leaf nodes from the package tree was something in the likeness of a practical suggestion, but I suppose I can simply make a pull request after applying the needed changes myself.

I am sorry to hear that you feel I have wasted your time. To make up for this, let me notify you that this specific repository contains an error in the documentation. Specifically, the following line:
```py
from borb.pdf.document import Document
```
is in error, since `borb` doesn't work like that. The correct line would be 
```
from borb.pdf.document.document import Document
```

This error occurs in every instance of  the import lines in `borb-examples` from section 2.2 of the book onwards.

**Comment by jorisschellekens** [comment] 2022-02-22 12:49
I know.
I am currently modifying the documentation to ensure all code examples work with the new imports.
