### ISSUE TITLE
Form data not printing correct values

### ISSUE THREAD

**Issue by aseams** [jorisschellekens/borb-examples#11] opened 2022-03-21 18:56 UTC
When creating a form with multiple `TextField`'s, their values will overwrite each other. Each of the `TextField`'s in my code have different `field_name` values (which I assume is similar to an ID in CSS).

Shown below is the pdf as seen in Chrome. I have added unique inputs for each `TextField`.
![image](https://user-images.githubusercontent.com/7917641/159340720-c4cf0473-7c31-46ed-ae81-12ecd8cf98a9.png)

Shown below is the print preview for this pdf with the same set of inputs as above. 
![image](https://user-images.githubusercontent.com/7917641/159340991-8088b314-11be-47ed-b3ad-fa69af6e4bbb.png)

When I tried to print this pdf (with all unique values), it printed the "print preview" version instead. If you save the PDF with unique values, it will also save the "print preview" version.

Example code:    (please note: actual table is much bigger, but this should produce the same result)
```
layout.add(
  FixedColumnWidthTable(
    number_of_columns=4,
    number_of_rows=2,
    margin_top=80,
    column_widths=[Decimal(2.1), Decimal(3), Decimal(0.5), Decimal(3)],
    vertical_alignment=Alignment.TOP,
  )
  .add(
    Paragraph(
      "User Name:",
      font="Helvetica-bold",
      font_size=11,
      padding_bottom=6
    )
  )
  .add(
    TextField(
      field_name="username",
      padding_top=Decimal(4),
      font_size=11,
      padding_bottom=6
    )
  )
  .add(
    Paragraph(
      "ID:",
      font="Helvetica-bold",
      font_size=11,
      padding_bottom=6
    )
  )
  .add(
    TextField(
      field_name="eid",
      padding_top=Decimal(4),
      font_size=11,
      padding_bottom=6
    )
  )
  .add(
    Paragraph(
      "Computer Name:",
      font="Helvetica-bold",
      font_size=11,
      padding_bottom=6
    )
  )
  .add(
    TableCell(
      TextField(
        field_name="newpcname",
        padding_top=Decimal(4),
        font_size=11,
        padding_bottom=6
      ),
      col_span=3
    )
  )
  .set_padding_on_all_cells(
  Decimal(3), Decimal(2), Decimal(0), Decimal(2))
  .no_borders()
)
```

**Comment by jorisschellekens** [comment] 2022-03-21 21:39
I am going to close this issue because it is a duplicate of #9 

You will also find my feedback in that issue.

Kind regards,
Joris Schellekens

**Closed as completed by jorisschellekens** 2022-03-21 21:39 UTC
