### ISSUE TITLE
Form displaying incorectly

### ISSUE THREAD

**Issue by laffen** [jorisschellekens/borb-examples#9] opened 2022-03-16 21:20 UTC
Form displaying incorrectly:

When creating forms, entered values will not show correctly after PDF is saved and reopened.  When you enter the textfield in edit-mode, the value previously entered will show.  Looks like the last entered value is displayed in all the textfields.  The same effect can be created with the following code:
    layout.add(
        FixedColumnWidthTable(number_of_columns=2, number_of_rows=4)
        .add(Paragraph("First Name:"))
        .add(TextField(field_name="firstname"))
        .add(Paragraph("Last Name:"))
        .add(TextField(field_name="lastname"))
        .add(Paragraph("Country"))
        .add(TextField(field_name="country",value="NaN"))   
        .set_padding_on_all_cells(Decimal(2), Decimal(2), Decimal(2), Decimal(2))
        .no_borders()
    )

When opening this pdf, all fields will show "NaN".

Python 3.10.3
borb-2.0.21
Platform Windows 10
Pdf tested in chrome and Acrobat Reade
[output_form.pdf](https://github.com/jorisschellekens/borb-examples/files/8274212/output_form.pdf)
r

**Comment by jorisschellekens** [comment] 2022-03-17 11:42
I'm tempted to say this is an Adobe issue.

When you open the pdf in notepad, you can see the form widget dictionaries. Their `V` (value) and `DV` (default value) entries are set correctly. According to the spec at least, only one of them is set and somehow Adobe displays the `V` entry for all of them.

I'll have a look at it later.

Kind regards,
Joris Schellekens

**Comment by BjornFJohansson** [comment] 2022-04-06 09:52
This seems to work ok in Xreader:

![image](https://user-images.githubusercontent.com/9726401/161947885-e1e46aec-d9b2-4d54-81a8-e1713f158e3b.png)

Opening in [Xreader 3.2.2](https://github.com/linuxmint/xreader)

![image](https://user-images.githubusercontent.com/9726401/161948372-3cadfc7d-39d6-4d27-827b-9c3f28ef4567.png)

Saving new info and opening again.

**Comment by jorisschellekens** [comment] 2022-04-06 12:25
I'm going to close this issue.

The PDF opens and works in Evince (the default ubuntu PDF viewer).
The PDF opens and works in xreader.
The PDF is created in accordance with the PDF spec.

These are very strong indications that the problem is indeed Adobe related, rather than borb related.

Kind regards,
Joris Schellekens

**Closed as completed by jorisschellekens** 2022-04-06 12:25 UTC
